import { lessons, patterns, words, questions } from './data.js';
import { firebaseConfig } from './firebase-config.js';

const KEY = 'aerotest-killer-v1';
const initial = { name: '', completedLessons: [], answers: 0, correct: 0, wrong: [], wrongWords: [], streak: 0, lastStudy: '', minutes: 0, examDate: '', config: {}, signedIn: false };
let state = load();
let route = location.hash.slice(1) || 'home';
let session = null;
let timerId = null;
let cloud = null;
let syncTimer = null;

function load(){ try{return {...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...initial}} }
function save(){ localStorage.setItem(KEY,JSON.stringify(state)); if(cloud){clearTimeout(syncTimer);syncTimer=setTimeout(syncCloud,500)} }
function h(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function go(next){location.hash=next}
function header(title, subtitle='AeroTest') { return `<header class="topbar"><button class="back" data-go="home" aria-label="Geri">‹</button><div class="page-title"><small>${h(subtitle)}</small><h1>${h(title)}</h1></div><div class="grow"></div></header>` }
function nav(active='home'){return `<nav class="nav"><button data-go="home" class="${active==='home'?'active':''}"><span>⌂</span>Ana Sayfa</button><button data-go="stats" class="${active==='stats'?'active':''}"><span>▥</span>İstatistik</button><button data-go="settings" class="${active==='settings'?'active':''}"><span>⚙</span>Ayarlar</button></nav>`}
function shell(content, active){return `<main class="shell">${content}${active?nav(active):''}</main>`}
function daysToExam(){if(!state.examDate)return null;return Math.max(0,Math.ceil((new Date(state.examDate+'T00:00:00')-new Date())/86400000))}
function progress(){return state.answers?Math.round(state.correct/state.answers*100):0}

function home(){
  const left=daysToExam();
  return shell(`<header class="topbar"><div class="brand"><div class="logo">✈</div><div class="brand-text"><strong>AeroTest Killer</strong><small>SHGM Dil Sınavı Hazırlık</small></div></div><div class="grow"></div>${state.signedIn?`<button class="avatar" data-go="settings">${h((state.name||'U')[0].toUpperCase())}</button>`:'<button class="login" data-action="login">🔑 Google ile giriş</button>'}</header>
  <section class="hero"><div class="eyebrow">Merhaba ${h(state.name||'👋')}</div><h1>Bugün ne çalışmak<br>istersin?</h1><button class="countdown" data-action="date"><span class="big">🗓️</span><span><strong>${left===null?'Tarih seçerek geri sayımı başlat':left+' gün kaldı'}</strong><small>${left===null?'Kartın herhangi bir yerine dokun':'Sınav tarihi: '+new Date(state.examDate+'T00:00:00').toLocaleDateString('tr-TR')}</small></span></button></section>
  <section class="grid"><button class="card mode featured wide" data-go="exam"><span class="art">⏱️</span><div><h3>Sınav Modu</h3><p>Süre baskısı altında gerçek sınav deneyimi.</p></div></button>
  <button class="card mode" data-go="lessons"><h3>Konulara Yönelik</h3><p>Sistem ve gramer odaklı çalışma.</p><span class="art">📖</span></button>
  <button class="card mode" data-go="patterns"><h3>Altın Kalıplar</h3><p>Kritik havacılık kalıplarını ezberle.</p><span class="art">🛩️</span></button>
  <button class="card mode" data-go="words"><h3>Kelime Çalışması</h3><p>Teknik havacılık kelimelerini güçlendir.</p><span class="art">🗂️</span></button>
  <button class="card mode" data-go="practice"><h3>Haftalık Test</h3><p>Karışık sorularla bilgini ölç.</p><span class="art">🏆</span></button></section>
  <section class="stats"><div class="stat"><strong>${state.answers}</strong><small>Soru Sayısı</small></div><div class="stat"><strong>${state.minutes}</strong><small>Dakika</small></div><div class="stat"><strong>${state.streak}</strong><small>Gün Serisi</small></div><div class="stat"><strong>%${progress()}</strong><small>Başarı</small></div></section>`, 'home');
}

function lessonsPage(){return shell(`${header('Konulara Yönelik Çalışma')}<section class="card intro"><h2>📘 Sistem ve Gramer Odaklı Pratik</h2><p class="copy">Güncel çalışma kılavuzundaki temel başlıklar, mobil ekranda kısa ve uygulanabilir derslere ayrıldı.</p></section><div>${lessons.map(l=>`<button class="card field-card" style="width:100%" data-go="lesson/${l.id}"><span class="emoji">${l.icon}</span><span><h3>${h(l.code+' · '+l.title)}</h3><p>${h(l.subtitle)}</p></span><span class="grow"></span><span>${state.completedLessons.includes(l.id)?'✓':'›'}</span></button>`).join('')}</div>`,false)}
function lessonPage(id){const l=lessons.find(x=>x.id===id)||lessons[0];return shell(`${header(l.title,l.code)}${l.sections.map((s,i)=>`<section class="card lesson-card"><span class="badge">${i+1}. bölüm</span><h2>${h(s.title)}</h2><p class="copy">${h(s.body)}</p><div class="example">${h(s.example)}</div></section>`).join('')}<button class="primary" data-action="complete-lesson" data-id="${l.id}">${state.completedLessons.includes(l.id)?'✓ TAMAMLANDI':'DERSİ TAMAMLA'}</button>`,false)}

function patternsPage(index=0){const p=patterns[index%patterns.length];return shell(`${header('Altın Kalıplar')}<div class="segmented"><button class="active">Tüm Kalıplar</button><button>★ Öncelikli</button></div><section class="card pattern-card"><small>FİZİKSEL DURUM</small><div class="cue">${h(p.cue)}</div><div class="meaning">${h(p.meaning)}</div><p class="example">${h(p.example)}</p><div class="tip">💡 ${h(p.tip)}</div></section><div class="row"><button class="primary" data-go="patterns/${(index-1+patterns.length)%patterns.length}">‹</button><button class="primary" data-go="patterns/${(index+1)%patterns.length}">›</button></div>`,false)}
function wordChoices(index){const correct=words[index][1];const pool=words.filter((_,i)=>i!==index).map(w=>w[1]);const wrong=[pool[(index*7+3)%pool.length],pool[(index*11+5)%pool.length],pool[(index*13+9)%pool.length]];return [correct,...wrong].sort((a,b)=>((a.length+index)%7)-((b.length+index)%7))}
function wordsPage(index=0,answerCode=''){index=index%words.length;const [en,tr,example='',module='Teknik Havacılık']=words[index];const choices=wordChoices(index);const selected=answerCode.startsWith('a')?Number(answerCode.slice(1)):null;const answered=Number.isInteger(selected);const correct=choices.indexOf(tr);return shell(`${header('Kelime Çalışması')}<div class="progress"><i style="width:${Math.round((index+1)/words.length*100)}%"></i></div><section class="card word-question"><span class="badge">${h(module)}</span><div class="word">${h(en)}</div><p class="copy">Bu kelimenin Türkçe anlamı nedir?</p></section><div>${choices.map((choice,i)=>`<button class="choice word-choice ${answered?(i===correct?'correct':i===selected?'wrong':'')}" data-word-answer="${i}" data-word-index="${index}" ${answered?'disabled':''}><b>${String.fromCharCode(65+i)})</b> ${h(choice)}</button>`).join('')}</div>${answered?`<div class="explanation word-explanation"><b>✓ Doğru cevap: ${String.fromCharCode(65+correct)} — ${h(tr)}</b>${example?`<p>${h(example)}</p>`:''}</div><div class="tip">💡 “${h(en)}” kelimesini teknik dokümandaki bağlamıyla birlikte hatırla.</div><button class="primary" data-go="words/${(index+1)%words.length}">SONRAKİ KELİME →</button>`:''}`,false)}

function setup(mode){const isExam=mode==='exam';return shell(`${header(isExam?'Sınav Modu':'Haftalık Test')}<section class="card intro"><h2>${isExam?'⏱️ Gerçek Sınav Deneyimi':'🏆 Karışık Pratik'}</h2><p>${isExam?'Süre baskısı altında kendini test et.':'Anında açıklamalarla eksiklerini gör.'}</p></section><section class="card"><h3>Soru sayısı</h3><div class="segmented" id="count">${[10,20,30,50].map(x=>`<button data-value="${x}" class="${x===20?'active':''}">${x}</button>`).join('')}</div>${isExam?'<h3>Sınav süresi</h3><div class="segmented" id="duration"><button data-value="30">30 dk</button><button data-value="60" class="active">60 dk</button></div>':''}</section><button class="primary" data-action="start" data-mode="${mode}">▶ ${isExam?'SINAVA':'ÇALIŞMAYA'} BAŞLA</button>`,false)}
function shuffled(source){return [...source].sort(()=>Math.random()-.5)}
function startQuiz(mode,count,duration){session={mode,items:shuffled(questions).slice(0,Math.min(count,questions.length)),index:0,selected:null,score:0,started:Date.now(),duration:duration*60,remaining:duration*60};location.hash='quiz';if(mode==='exam')startTimer()}
function startTimer(){clearInterval(timerId);timerId=setInterval(()=>{if(!session)return;session.remaining--;const el=document.querySelector('.timer');if(el)el.textContent=formatTime(session.remaining);if(session.remaining<=0)finishQuiz()},1000)}
function formatTime(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function quizPage(){if(!session)return setup('practice');const q=session.items[session.index];if(!q)return resultPage();const answered=session.selected!==null;return shell(`${header('Soru '+(session.index+1)+' / '+session.items.length,session.mode==='exam'?'Sınav Modu':'Pratik')}<div class="quiz-head"><span class="badge">${h(q.type)}</span>${session.mode==='exam'?`<span class="timer">${formatTime(session.remaining)}</span>`:`<span>Doğru: ${session.score}</span>`}</div><div class="progress"><i style="width:${Math.round(session.index/session.items.length*100)}%"></i></div><h2 class="question">${h(q.q)}</h2><div>${q.o.map((o,i)=>`<button class="choice ${answered?(i===q.a?'correct':i===session.selected?'wrong':''):''}" data-answer="${i}" ${answered?'disabled':''}><b>${String.fromCharCode(65+i)})</b> ${h(o)}</button>`).join('')}</div>${answered&&session.mode!=='exam'?`<div class="explanation">${session.selected===q.a?'✓ Doğru.':'✕ Doğru cevap: '+String.fromCharCode(65+q.a)} ${h(q.n)}</div>`:''}${answered?'<button class="primary" data-action="next">'+(session.index===session.items.length-1?'SONUCU GÖR':'SONRAKİ SORU')+'</button>':''}`,false)}
function answer(i){if(!session||session.selected!==null)return;const q=session.items[session.index];session.selected=i;state.answers++;if(i===q.a){session.score++;state.correct++;state.wrong=state.wrong.filter(x=>x!==q.id)}else if(!state.wrong.includes(q.id))state.wrong.push(q.id);touchStudy();save();render()}
function next(){session.index++;session.selected=null;if(session.index>=session.items.length)finishQuiz();else render()}
function finishQuiz(){if(!session)return;clearInterval(timerId);state.minutes+=Math.max(1,Math.round((Date.now()-session.started)/60000));save();route='result';history.replaceState(null,'','#result');render()}
function resultPage(){if(!session)return home();const pct=Math.round(session.score/session.items.length*100);return shell(`${header('Sonuç')}<section class="card intro" style="text-align:center"><div style="font-size:55px">${pct>=70?'🏆':'📘'}</div><h2>%${pct} başarı</h2><p>${session.items.length} soruda ${session.score} doğru, ${session.items.length-session.score} yanlış.</p><div class="progress"><i style="width:${pct}%"></i></div></section><button class="primary" data-go="practice">YENİ TEST</button><button class="primary danger" data-go="home">ANA SAYFAYA DÖN</button>`,false)}

function statsPage(){const groups=['Yapı','Çeviri','Kelime'].map(type=>({type,ids:state.wrong.filter(id=>questions.find(q=>q.id===id)?.type===type)}));return shell(`${header('İstatistikler')}<section class="grid"><div class="card"><small>Toplam soru</small><h2>${state.answers}</h2></div><div class="card"><small>Başarı</small><h2>%${progress()}</h2></div><div class="card"><small>Yanlış havuzu</small><h2>${state.wrong.length+state.wrongWords.length}</h2></div><div class="card"><small>Tamamlanan konu</small><h2>${state.completedLessons.length}/${lessons.length}</h2></div></section><h3 class="section-title">YANLIŞ YAPTIKLARIM</h3>${groups.map(g=>`<button class="card field-card wrong-category" style="width:100%" data-action="wrong-category" data-category="${g.type}" ${g.ids.length?'':'disabled'}><span class="emoji">${g.type==='Yapı'?'🧩':g.type==='Çeviri'?'🌐':'🔤'}</span><span><h3>${g.type} Yanlışlarım</h3><p>${g.ids.length?g.ids.length+' soru tekrar edilmeyi bekliyor.':'Bu kategoride yanlış yok.'}</p></span><span class="grow"></span><b>${g.ids.length}</b></button>`).join('')}<button class="card field-card wrong-category" style="width:100%" data-action="wrong-words" ${state.wrongWords.length?'':'disabled'}><span class="emoji">📚</span><span><h3>Kelime Çalışması Yanlışlarım</h3><p>${state.wrongWords.length?state.wrongWords.length+' kelime tekrar edilmeyi bekliyor.':'Yanlış kelime yok.'}</p></span><span class="grow"></span><b>${state.wrongWords.length}</b></button>`, 'stats')}
function settingsPage(){return shell(`${header('Ayarlar')}<section class="card settings"><div class="account"><div class="avatar">${h((state.name||'U')[0].toUpperCase())}</div><div><strong>${h(state.name||'Misafir kullanıcı')}</strong><p class="copy" style="margin:3px 0">${state.signedIn?'İlerleme buluta eşitlenebilir.':'İlerleme bu cihazda saklanıyor.'}</p></div></div><label>Görünen ad</label><input id="name" value="${h(state.name)}" placeholder="Adınız"><label>Sınav tarihi</label><input id="exam-date" type="date" value="${h(state.examDate)}"><button class="primary" data-action="save-settings">KAYDET</button>${state.signedIn?'<button class="primary danger" data-action="logout">OTURUMU KAPAT</button>':'<button class="primary" data-action="login">GOOGLE İLE GİRİŞ</button>'}</section><button class="card danger" style="width:100%;margin-top:14px" data-action="reset">Tüm yerel ilerlemeyi sıfırla</button>`, 'settings')}
function touchStudy(){const today=new Date().toISOString().slice(0,10);if(state.lastStudy!==today){const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);state.streak=state.lastStudy===yesterday?state.streak+1:1;state.lastStudy=today}}

function loginModal(){const ready=Boolean(firebaseConfig.apiKey);document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap"><div class="modal"><h2>Google ile giriş</h2><p class="copy">${ready?'Google hesabınızla giriş yaptığınızda ilerlemeniz hesabınıza bağlanır.':'Firebase yapılandırması henüz girilmemiş. Şimdilik ilerlemeniz bu cihazda kesintisiz saklanabilir.'}</p>${ready?'<button class="primary" data-action="google-login">GOOGLE İLE DEVAM ET</button>':'<button class="primary" data-action="demo-login">YEREL PROFİLİ ETKİNLEŞTİR</button>'}<button class="secondary" data-action="close-modal">VAZGEÇ</button></div></div>`)}

async function initFirebase(){
  if(!firebaseConfig.apiKey)return;
  try{
    const appMod=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js');
    const authMod=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js');
    const dbMod=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js');
    const app=appMod.initializeApp(firebaseConfig);const auth=authMod.getAuth(app);const db=dbMod.getFirestore(app);
    await authMod.setPersistence(auth,authMod.browserLocalPersistence);
    cloud={auth,db,authMod,dbMod,user:null};
    authMod.onAuthStateChanged(auth,async user=>{cloud.user=user;if(user){state.signedIn=true;state.name=state.name||user.displayName||'';const ref=dbMod.doc(db,'users',user.uid);const snap=await dbMod.getDoc(ref);if(snap.exists())state={...state,...snap.data(),signedIn:true,name:state.name||user.displayName||''};localStorage.setItem(KEY,JSON.stringify(state));render()}else if(state.signedIn){state.signedIn=false;localStorage.setItem(KEY,JSON.stringify(state));render()}});
  }catch(error){console.warn('Firebase başlatılamadı',error)}
}
async function googleLogin(){if(!cloud){await initFirebase()}if(!cloud){toast('Firebase yapılandırması gerekli.');return}try{const provider=new cloud.authMod.GoogleAuthProvider();await cloud.authMod.signInWithPopup(cloud.auth,provider);document.querySelector('.modal-wrap')?.remove();toast('Google hesabına bağlandı.')}catch(error){toast(error.code==='auth/popup-blocked'?'Açılır pencereye izin verin.':'Google girişi tamamlanamadı.') }}
async function syncCloud(){if(!cloud?.user)return;try{const clean={...state};delete clean.config;await cloud.dbMod.setDoc(cloud.dbMod.doc(cloud.db,'users',cloud.user.uid),clean,{merge:true})}catch(error){console.warn('İlerleme eşitlenemedi',error)}}

function render(){route=location.hash.slice(1)||route||'home';const [base,param,extra]=route.split('/');let html;switch(base){case'home':html=home();break;case'lessons':html=lessonsPage();break;case'lesson':html=lessonPage(param);break;case'patterns':html=patternsPage(Number(param)||0);break;case'words':html=wordsPage(Number(param)||0,extra||'');break;case'exam':html=setup('exam');break;case'practice':html=setup('practice');break;case'quiz':html=quizPage();break;case'result':html=resultPage();break;case'stats':html=statsPage();break;case'settings':html=settingsPage();break;default:html=home()}document.querySelector('#app').innerHTML=html;window.scrollTo(0,0)}

document.addEventListener('click',e=>{
  const wordAnswer=e.target.closest('[data-word-answer]');
  if(wordAnswer){const index=Number(wordAnswer.dataset.wordIndex);const selected=Number(wordAnswer.dataset.wordAnswer);const correct=wordChoices(index).indexOf(words[index][1]);state.answers++;if(selected===correct){state.correct++;state.wrongWords=state.wrongWords.filter(i=>i!==index)}else if(!state.wrongWords.includes(index)){state.wrongWords.push(index)}touchStudy();save();go(`words/${index}/a${selected}`);return}
  const category=e.target.closest('[data-action="wrong-category"]');
  if(category){const items=questions.filter(q=>q.type===category.dataset.category&&state.wrong.includes(q.id));if(items.length){session={mode:'practice',items:shuffled(items),index:0,selected:null,score:0,started:Date.now(),remaining:0};go('quiz')}return}
  const wrongWords=e.target.closest('[data-action="wrong-words"]');
  if(wrongWords&&state.wrongWords.length){go(`words/${state.wrongWords[0]}`)}
});

document.addEventListener('click',e=>{const goEl=e.target.closest('[data-go]');if(goEl){go(goEl.dataset.go);return}const ans=e.target.closest('[data-answer]');if(ans){answer(Number(ans.dataset.answer));return}const button=e.target.closest('[data-action]');if(!button)return;switch(button.dataset.action){case'login':loginModal();break;case'google-login':googleLogin();break;case'close-modal':document.querySelector('.modal-wrap')?.remove();break;case'demo-login':state.signedIn=true;state.name=state.name||'Onur';save();document.querySelector('.modal-wrap')?.remove();render();toast('Profil bu cihazda etkinleştirildi.');break;case'logout':if(cloud?.user)cloud.authMod.signOut(cloud.auth);else{state.signedIn=false;save();render()}break;case'date':go('settings');break;case'complete-lesson':if(!state.completedLessons.includes(button.dataset.id))state.completedLessons.push(button.dataset.id);touchStudy();save();render();toast('Ders tamamlandı.');break;case'save-settings':state.name=document.querySelector('#name').value.trim();state.examDate=document.querySelector('#exam-date').value;save();toast('Ayarlar kaydedildi.');render();break;case'reset':if(confirm('Tüm ilerleme kalıcı olarak silinsin mi?')){state={...initial};save();render()}break;case'start':{const count=Number(document.querySelector('#count .active')?.dataset.value||20);const duration=Number(document.querySelector('#duration .active')?.dataset.value||60);startQuiz(button.dataset.mode,count,duration);break}case'next':next();break;case'wrong-quiz':{const items=questions.filter(q=>state.wrong.includes(q.id));session={mode:'practice',items:shuffled(items),index:0,selected:null,score:0,started:Date.now(),remaining:0};go('quiz');break}}});
document.addEventListener('click',e=>{const b=e.target.closest('.segmented button[data-value]');if(!b)return;b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
window.addEventListener('hashchange',render);
window.addEventListener('beforeunload',save);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
initFirebase();
